### ISSUE TITLE
Matching Code to Paper

### ISSUE THREAD

**Issue by rsonthal** [mblondel/smooth-ot#2]
The dual solver is to solve (7) (from the paper) and the semi-dual is to solve (10) (from the paper)? The code on GitHub does not include solvers for (13) or (14)? 

Thank you for help in advance.

**Comment by mblondel** [comment]
Indeed, that's correct. (13) is very easy to solve using [LBFGS-B](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html) from SciPy though.
